Fix user profile bloc unit tests
breez/c-breez pull request #462
Opened 2023-01-31 14:20 UTC by ademar111190

Fixes https://github.com/breez/c-breez/issues/459

I'm adding a "UnitLogTree" to take advantage of fimber on unit tests; it helped me a lot on these tests.

2023-01-31 14:27 UTC, erdemyerebasmaz approved these changes
LGTM

2023-01-31 14:30 UTC, ubbabeck approved these changes
LGTM too 🚀

2023-02-01 09:32 UTC, ubbabeck requested changes
Do you think the workflow build will success when these are removed?

2023-02-01 09:32 UTC, ubbabeck commented on test/unit_logger.dart
> +    print("$tag [$level] $message");
the dart analyser tool does not like when we use print in production

2023-02-01 09:32 UTC, ubbabeck commented on test/unit_logger.dart
> +    if (stacktrace != null) print(stacktrace);
same here

2023-02-01 09:32 UTC, ubbabeck commented on test/unit_logger.dart
> +    if (ex != null) print(ex);
```
info • test/unit_logger.dart:18:21 • Don't invoke 'print' in production
          code. Try using a logging framework. • avoid_print
```

2023-02-01 11:57 UTC, erdemyerebasmaz approved these changes

2023-02-01 12:10 UTC, ubbabeck approved these changes

2023-02-01 12:12 UTC, merged