Android notifications logging
breez/c-breez pull request #745
Opened 2023-12-19 18:36 UTC by erdemyerebasmaz

2023-12-20 20:51 UTC, roeierez commented on android/app/src/main/kotlin/com/cBreez/client/MainActivity.kt
> +        configureLogger()
Is the Activity created when the app is killed and the notification is received?

2023-12-21 17:42 UTC, erdemyerebasmaz commented on ios/Breez Notification Service Extension/NotificationService.swift
> +        let extensionLogFile = logsDir.appendingPathComponent("ios-extension-\(Date().timeIntervalSince1970).log")
TODO: Add ios extension logs under `logs/ios-extension/` directory and rename file name to timestamp

2023-12-21 18:14 UTC, roeierez requested changes

2023-12-21 18:14 UTC, roeierez commented on android/app/src/main/java/com/cBreez/client/BreezFCMService.kt
> +        configureLogger()
This creates a logger and configure it with every notification. It is better IMO to configure it once and set it statically.

2023-12-22 10:36 UTC, roeierez approved these changes

2023-12-26 09:49 UTC, merged